export const AUTH_START = "AUTH_START";
export const AUTH_SUCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "AUTH_REDIRECT_PATH";

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const FETCH_START = "FETCH_START";
export const FETCH_FEED_SUCESS = "FETCH_FEED_SUCCESS";
export const FETCH_FEED_FAIL = "FETCH_FEED_FAIL";
export const FETCH_SUGGESTIONS_SUCESS = "FETCH_SUGGESTIONS_SUCCESS";
export const FETCH_SUGGESTIONS_FAIL = "FETCH_SUGGESTIONS_FAIL";

export const LIKE_POST = "LIKE_POST";
export const DISLIKE_POST = "DISLIKE_POST";

export const FETCH_EXPLORE_START = "FETCH_EXPLORE_START";
export const FETCH_EXPLORE_SUCCESS = "FETCH_EXPLORE_SUCCESS";
export const FETCH_EXPLORE_FAIL = "FETCH_EXPLORE_FAIL";

export const FETCH_POST_DETAILS_SUCCESS = "FETCH_POST_DETAIL_SUCCESS";
export const FETCH_POST_DETAILS_FAIL = "FETCH_POST_DETAIL_FAIL"; 

export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";